import { spawn } from "node:child_process";
import { existsSync } from "node:fs";
import { chmod, mkdir, mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { beforeAll, describe, expect, it } from "vitest";
import { parse as parseYaml, stringify as stringifyYaml } from "yaml";

/**
 * L4 CLI binary smoke tests.
 *
 * These exercise the *built* `dist/index.js` as a real subprocess against a
 * temp workspace, which catches a layer that the in-process `tests/cli/*`
 * suite cannot: packaging miss, shebang/permissions, Node ESM resolution at
 * runtime, CLI arg parser quoting, and exit-code propagation. The LLM step
 * is stubbed via a fake `claude` binary on PATH so we never hit the network
 * or burn tokens.
 *
 * Layer rationale (see #73): tests/cli/* covers "hexagonal e2e" (adapter
 * mocked in-process); tests/e2e/* covers "binary smoke" (whole CLI spawned
 * as a subprocess, only the agent CLI itself is faked).
 */

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");
const CLI = join(REPO_ROOT, "dist", "index.js");

/**
 * Spawn the built CLI and capture stdout/stderr/exit-code.
 *
 * Tests are responsible for asserting on the returned shape; we never throw
 * on non-zero exit so the assertion message can include the captured output.
 */
async function runCli(
  args: string[],
  options: { cwd: string; extraPath?: string },
): Promise<{ code: number; stdout: string; stderr: string }> {
  return new Promise((resolveProm, reject) => {
    const env: NodeJS.ProcessEnv = { ...process.env };
    if (options.extraPath) {
      env.PATH = `${options.extraPath}:${env.PATH ?? ""}`;
    }
    const child = spawn("node", [CLI, ...args], {
      cwd: options.cwd,
      env,
      stdio: ["pipe", "pipe", "pipe"],
    });
    let stdout = "";
    let stderr = "";
    child.stdout.on("data", (c) => {
      stdout += c.toString();
    });
    child.stderr.on("data", (c) => {
      stderr += c.toString();
    });
    child.on("error", reject);
    child.on("close", (code) => {
      resolveProm({ code: code ?? 0, stdout, stderr });
    });
    child.stdin.end();
  });
}

/**
 * Write a fake `claude` binary that reads the adapter's JSON payload from
 * stdin and produces a minimal-but-valid v(N+1) Markdown report at the
 * requested outputPath. Used for research (no prevResearch) and update (with
 * prevResearch); we discriminate on payload shape.
 *
 * Mirrors the structure pin'd by tests/agents/claude-code.test.ts: stdin is
 * a single JSON document with agent / templateId / templateBody / items /
 * outputPath, plus prevResearch for update.
 */
async function installFakeClaude(binDir: string): Promise<void> {
  await mkdir(binDir, { recursive: true });
  const script = `#!/usr/bin/env node
const fs = require("node:fs");
const path = require("node:path");

let stdin = "";
process.stdin.setEncoding("utf8");
process.stdin.on("data", (c) => { stdin += c; });
process.stdin.on("end", () => {
  let req;
  try { req = JSON.parse(stdin); } catch (e) {
    console.error("fake-claude: bad stdin:", e.message);
    process.exit(2);
  }
  const { outputPath, prevResearch, agent, items } = req;
  if (!outputPath) { console.error("fake-claude: no outputPath"); process.exit(2); }
  const newId = path.basename(outputPath, ".md");
  const isUpdate = prevResearch !== undefined;
  const fm = isUpdate ? prevResearch.frontmatter : null;
  const itemIds = (fm ? fm.itemIds : items.map((i) => i.id))
    .map((id) => "  - " + id)
    .join("\\n");
  const createdAt = isUpdate ? fm.createdAt : new Date().toISOString();
  const templateId = isUpdate ? fm.templateId : (req.templateId || "default");
  const supersedes = isUpdate ? fm.id : null;
  const yaml = [
    "---",
    "id: " + newId,
    "itemIds:",
    itemIds,
    "agent: " + agent,
    "templateId: " + templateId,
    "createdAt: " + createdAt,
    "updatedAt: " + new Date().toISOString(),
    "reviewedAt: null",
    "reviewedBy: null",
    "supersedes: " + (supersedes === null ? "null" : supersedes),
    "---",
    "",
    "# " + (isUpdate ? "v+1 update" : "v1 research") + " (smoke)",
    "",
    "Generated by fake claude binary for L4 smoke. agent=" + agent,
    ""
  ].join("\\n");
  fs.writeFileSync(outputPath, yaml, "utf8");
  console.log("fake-claude: wrote " + outputPath);
});
`;
  const scriptPath = join(binDir, "claude");
  await writeFile(scriptPath, script, "utf8");
  await chmod(scriptPath, 0o755);
}

interface Frontmatter {
  id: string;
  itemIds: string[];
  agent: string;
  templateId: string;
  createdAt: string;
  updatedAt: string | null;
  reviewedAt: string | null;
  reviewedBy: string | null;
  supersedes: string | null;
}

/** Lightweight frontmatter parser sufficient for what the fake binary writes. */
function parseFrontmatter(md: string): { fm: Frontmatter; body: string } {
  const match = md.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!match) throw new Error("no frontmatter");
  return { fm: parseYaml(match[1]) as Frontmatter, body: match[2] };
}

describe("e2e/cli (binary smoke)", () => {
  beforeAll(() => {
    // CI builds dist/ before tests (typecheck → build → test). Locally, the
    // developer must run `pnpm build` first; we fail loudly here rather than
    // silently skip so the gap is obvious.
    if (!existsSync(CLI)) {
      throw new Error(
        `dist/index.js not found at ${CLI}. Run \`pnpm build\` before \`pnpm run test\`, or use \`pnpm run prepublishOnly\` which chains build → typecheck → test.`,
      );
    }
  });

  describe("scenario A: init", () => {
    it("creates the canonical workspace layout and copies bundled skills", async () => {
      const workdir = await mkdtemp(join(tmpdir(), "aw-e2e-init-"));
      const result = await runCli(["init"], { cwd: workdir });

      expect(result.code, `stderr: ${result.stderr}`).toBe(0);
      // Sanity: status message + skill copy log lines on stdout.
      expect(result.stdout).toContain("init: workspace ready");
      expect(result.stdout).toContain("init: skills copied");

      for (const dir of ["sources", "state", "items", "research", "templates"]) {
        expect(existsSync(join(workdir, dir))).toBe(true);
      }
      for (const skill of ["research", "review", "update"]) {
        expect(existsSync(join(workdir, ".agents", "skills", skill, "SKILL.md"))).toBe(true);
      }
    });
  });

  describe("scenario B: source add / list / remove", () => {
    it("round-trips a source through add → list → remove", async () => {
      const workdir = await mkdtemp(join(tmpdir(), "aw-e2e-source-"));
      await runCli(["init"], { cwd: workdir });

      const add = await runCli(
        ["source", "add", "smoke-blog", "--kind", "rss", "--url", "https://example.com/feed.xml"],
        { cwd: workdir },
      );
      expect(add.code, `stderr: ${add.stderr}`).toBe(0);
      expect(existsSync(join(workdir, "sources", "smoke-blog.yaml"))).toBe(true);

      const list = await runCli(["source", "list"], { cwd: workdir });
      expect(list.code, `stderr: ${list.stderr}`).toBe(0);
      expect(list.stdout).toContain("smoke-blog");
      expect(list.stdout).toContain("rss");

      const remove = await runCli(["source", "remove", "smoke-blog"], { cwd: workdir });
      expect(remove.code, `stderr: ${remove.stderr}`).toBe(0);
      expect(existsSync(join(workdir, "sources", "smoke-blog.yaml"))).toBe(false);
    });
  });

  describe("scenario C: dismiss (LLM-free)", () => {
    it("transitions a detected item to dismissed", async () => {
      const workdir = await mkdtemp(join(tmpdir(), "aw-e2e-dismiss-"));
      await runCli(["init"], { cwd: workdir });

      const itemId = "smoke-item-abcdef12";
      const sourceId = "smoke-source";
      await mkdir(join(workdir, "items", sourceId), { recursive: true });
      await writeFile(
        join(workdir, "items", sourceId, `${itemId}.yaml`),
        stringifyYaml({
          id: itemId,
          sourceId,
          title: "Smoke item",
          url: "https://example.com/smoke",
          fetchedAt: "2026-05-15T00:00:00.000Z",
          matchedKeywords: ["smoke"],
          status: "detected",
        }),
        "utf8",
      );

      const result = await runCli(["dismiss", itemId], { cwd: workdir });
      expect(result.code, `stderr: ${result.stderr}`).toBe(0);

      const after = parseYaml(
        await readFile(join(workdir, "items", sourceId, `${itemId}.yaml`), "utf8"),
      );
      expect(after.status).toBe("dismissed");
    });
  });

  describe("scenario D: research --agent claude-code (fake binary)", () => {
    it("generates a valid v1 research file and transitions item to researched", async () => {
      const workdir = await mkdtemp(join(tmpdir(), "aw-e2e-research-"));
      const binDir = join(workdir, "_bin");
      await installFakeClaude(binDir);
      await runCli(["init"], { cwd: workdir });

      const itemId = "smoke-item-12345678";
      const sourceId = "smoke-source";
      await mkdir(join(workdir, "items", sourceId), { recursive: true });
      await writeFile(
        join(workdir, "items", sourceId, `${itemId}.yaml`),
        stringifyYaml({
          id: itemId,
          sourceId,
          title: "Smoke item for research",
          url: "https://example.com/smoke",
          fetchedAt: "2026-05-15T00:00:00.000Z",
          matchedKeywords: ["smoke"],
          status: "detected",
        }),
        "utf8",
      );

      const result = await runCli(["research", itemId, "--agent", "claude-code"], {
        cwd: workdir,
        extraPath: binDir,
      });
      expect(result.code, `stderr: ${result.stderr}\nstdout: ${result.stdout}`).toBe(0);

      // Item status transitioned.
      const item = parseYaml(
        await readFile(join(workdir, "items", sourceId, `${itemId}.yaml`), "utf8"),
      );
      expect(item.status).toBe("researched");

      // Research file was written with valid frontmatter (id contains
      // YYYYMMDD prefix + sourceId-slug-of-title + _v1).
      const researchMatch = result.stdout.match(/research\/([^.\s]+\.md)/);
      expect(researchMatch).not.toBeNull();
      const researchPath = join(workdir, "research", researchMatch?.[1] ?? "MISSING");
      expect(existsSync(researchPath)).toBe(true);
      const { fm } = parseFrontmatter(await readFile(researchPath, "utf8"));
      expect(fm.agent).toBe("claude-code");
      expect(fm.itemIds).toEqual([itemId]);
      expect(fm.supersedes).toBeNull();
      expect(fm.reviewedAt).toBeNull();
      expect(fm.reviewedBy).toBeNull();
      // v1 invariant: id ends in _v1.
      expect(fm.id).toMatch(/_v1$/);
    });
  });

  describe("scenario E: update --agent claude-code (fake binary, supersedes + status-invariance)", () => {
    it("generates v2 with supersedes pointing to v1; items.yaml status is unchanged", async () => {
      const workdir = await mkdtemp(join(tmpdir(), "aw-e2e-update-"));
      const binDir = join(workdir, "_bin");
      await installFakeClaude(binDir);
      await runCli(["init"], { cwd: workdir });

      const itemId = "smoke-item-aabbccdd";
      const sourceId = "smoke-source";
      await mkdir(join(workdir, "items", sourceId), { recursive: true });
      await writeFile(
        join(workdir, "items", sourceId, `${itemId}.yaml`),
        stringifyYaml({
          id: itemId,
          sourceId,
          title: "Smoke item for update",
          url: "https://example.com/smoke",
          fetchedAt: "2026-05-15T00:00:00.000Z",
          matchedKeywords: ["smoke"],
          status: "reviewed",
        }),
        "utf8",
      );

      // Hand-craft a v1 research file. (We skip running the research
      // subcommand first to keep scenario E isolated and fast.)
      const v1Id = `20260510_smoke-source-smoke-item-for-update_v1`;
      const v1Path = join(workdir, "research", `${v1Id}.md`);
      const v1Yaml = stringifyYaml({
        id: v1Id,
        itemIds: [itemId],
        agent: "claude-code",
        templateId: "default",
        createdAt: "2026-05-10T00:00:00.000Z",
        updatedAt: null,
        reviewedAt: "2026-05-12T00:00:00.000Z",
        reviewedBy: "codex-cli",
        supersedes: null,
      });
      await writeFile(v1Path, `---\n${v1Yaml}---\n\n# v1 body\n`, "utf8");

      const result = await runCli(["update", v1Id, "--agent", "claude-code"], {
        cwd: workdir,
        extraPath: binDir,
      });
      expect(result.code, `stderr: ${result.stderr}\nstdout: ${result.stdout}`).toBe(0);

      // v2 file exists with supersedes pointing at v1.
      const v2Path = join(workdir, "research", `${v1Id.replace(/_v1$/, "_v2")}.md`);
      expect(existsSync(v2Path)).toBe(true);
      const { fm: v2Fm } = parseFrontmatter(await readFile(v2Path, "utf8"));
      expect(v2Fm.supersedes).toBe(v1Id);
      // v+1 invariant: review state reset (ADR-0003).
      expect(v2Fm.reviewedAt).toBeNull();
      expect(v2Fm.reviewedBy).toBeNull();
      // createdAt preserved from predecessor.
      expect(v2Fm.createdAt).toBe("2026-05-10T00:00:00.000Z");

      // ADR-0008 invariance: items.yaml status is unchanged (still reviewed).
      const item = parseYaml(
        await readFile(join(workdir, "items", sourceId, `${itemId}.yaml`), "utf8"),
      );
      expect(item.status).toBe("reviewed");

      // Immutable history: v1 file unchanged.
      const { fm: v1Fm } = parseFrontmatter(await readFile(v1Path, "utf8"));
      expect(v1Fm.reviewedBy).toBe("codex-cli");
      expect(v1Fm.supersedes).toBeNull();
    });
  });
});
