import { spawn } from "node:child_process";
import { existsSync, readdirSync } from "node:fs";
import { chmod, mkdir, mkdtemp, readFile, writeFile } from "node:fs/promises";
import { type AddressInfo, createServer, type Server } from "node:http";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { beforeAll, describe, expect, it } from "vitest";
import { parse as parseYaml, stringify as stringifyYaml } from "yaml";

/**
 * L4 CLI binary smoke tests.
 *
 * These exercise the *built* `dist/index.js` as a real subprocess against a
 * temp workspace, which catches a layer that the in-process `tests/cli/*`
 * suite cannot: packaging miss, shebang/permissions, Node ESM resolution at
 * runtime, CLI arg parser quoting, and exit-code propagation. The LLM step
 * is stubbed via a fake `claude` binary on PATH so we never hit the network
 * or burn tokens.
 *
 * Layer rationale (see #73): tests/cli/* covers "hexagonal e2e" (adapter
 * mocked in-process); tests/e2e/* covers "binary smoke" (whole CLI spawned
 * as a subprocess, only the agent CLI itself is faked).
 */

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");
const CLI = join(REPO_ROOT, "dist", "index.js");

/**
 * Spawn the built CLI and capture stdout/stderr/exit-code.
 *
 * Tests are responsible for asserting on the returned shape; we never throw
 * on non-zero exit so the assertion message can include the captured output.
 */
async function runCli(
  args: string[],
  options: { cwd: string; extraPath?: string; extraEnv?: Record<string, string> },
): Promise<{ code: number; stdout: string; stderr: string }> {
  return new Promise((resolveProm, reject) => {
    const env: NodeJS.ProcessEnv = { ...process.env };
    if (options.extraPath) {
      env.PATH = `${options.extraPath}:${env.PATH ?? ""}`;
    }
    if (options.extraEnv) {
      // Extra env is layered on top of the inherited process.env so a test
      // can flip RADAR_FETCH_HOST_ALLOWLIST=127.0.0.1 just for one CLI call
      // (the SSRF blocklist in src/core/feeds/_fetch.ts is opt-in here).
      Object.assign(env, options.extraEnv);
    }
    const child = spawn("node", [CLI, ...args], {
      cwd: options.cwd,
      env,
      stdio: ["pipe", "pipe", "pipe"],
    });
    let stdout = "";
    let stderr = "";
    child.stdout.on("data", (c) => {
      stdout += c.toString();
    });
    child.stderr.on("data", (c) => {
      stderr += c.toString();
    });
    child.on("error", reject);
    child.on("close", (code) => {
      resolveProm({ code: code ?? 0, stdout, stderr });
    });
    child.stdin.end();
  });
}

/**
 * Write a fake `claude` binary that reads the adapter's JSON payload from
 * stdin and produces a minimal-but-valid v(N+1) Markdown report at the
 * requested outputPath. Used for research (no prevResearch) and update (with
 * prevResearch); we discriminate on payload shape.
 *
 * Mirrors the structure pin'd by tests/agents/claude-code.test.ts: stdin is
 * a single JSON document with agent / templateId / templateBody / items /
 * outputPath, plus prevResearch for update.
 */
async function installFakeClaude(binDir: string): Promise<void> {
  await mkdir(binDir, { recursive: true });
  const script = `#!/usr/bin/env node
const fs = require("node:fs");
const path = require("node:path");

let stdin = "";
process.stdin.setEncoding("utf8");
process.stdin.on("data", (c) => { stdin += c; });
process.stdin.on("end", () => {
  let req;
  try { req = JSON.parse(stdin); } catch (e) {
    console.error("fake-claude: bad stdin:", e.message);
    process.exit(2);
  }
  const { outputPath, prevResearch, agent, items } = req;
  if (!outputPath) { console.error("fake-claude: no outputPath"); process.exit(2); }
  const newId = path.basename(outputPath, ".md");
  const isUpdate = prevResearch !== undefined;
  const fm = isUpdate ? prevResearch.frontmatter : null;
  const itemIds = (fm ? fm.itemIds : items.map((i) => i.id))
    .map((id) => "  - " + id)
    .join("\\n");
  const createdAt = isUpdate ? fm.createdAt : new Date().toISOString();
  const templateId = isUpdate ? fm.templateId : (req.templateId || "default");
  const supersedes = isUpdate ? fm.id : null;
  const yaml = [
    "---",
    "id: " + newId,
    "itemIds:",
    itemIds,
    "agent: " + agent,
    "templateId: " + templateId,
    "createdAt: " + createdAt,
    "updatedAt: " + new Date().toISOString(),
    "reviewedAt: null",
    "reviewedBy: null",
    "supersedes: " + (supersedes === null ? "null" : supersedes),
    "---",
    "",
    "# " + (isUpdate ? "v+1 update" : "v1 research") + " (smoke)",
    "",
    "Generated by fake claude binary for L4 smoke. agent=" + agent,
    ""
  ].join("\\n");
  fs.writeFileSync(outputPath, yaml, "utf8");
  console.log("fake-claude: wrote " + outputPath);
});
`;
  const scriptPath = join(binDir, "claude");
  await writeFile(scriptPath, script, "utf8");
  await chmod(scriptPath, 0o755);
}

interface Frontmatter {
  id: string;
  itemIds: string[];
  agent: string;
  templateId: string;
  createdAt: string;
  updatedAt: string | null;
  reviewedAt: string | null;
  reviewedBy: string | null;
  supersedes: string | null;
}

/** Lightweight frontmatter parser sufficient for what the fake binary writes. */
function parseFrontmatter(md: string): { fm: Frontmatter; body: string } {
  const match = md.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!match) throw new Error("no frontmatter");
  return { fm: parseYaml(match[1]) as Frontmatter, body: match[2] };
}

describe("e2e/cli (binary smoke)", () => {
  beforeAll(() => {
    // CI builds dist/ before tests (typecheck → build → test). Locally, the
    // developer must run `pnpm build` first; we fail loudly here rather than
    // silently skip so the gap is obvious.
    if (!existsSync(CLI)) {
      throw new Error(
        `dist/index.js not found at ${CLI}. Run \`pnpm build\` before \`pnpm run test\`, or use \`pnpm run prepublishOnly\` which chains build → typecheck → test.`,
      );
    }
  });

  describe("scenario A: init", () => {
    it("creates the canonical workspace layout and copies bundled skills (engine + claude discovery)", async () => {
      const workdir = await mkdtemp(join(tmpdir(), "aw-e2e-init-"));
      const result = await runCli(["init"], { cwd: workdir });

      expect(result.code, `stderr: ${result.stderr}`).toBe(0);
      // Sanity: status message + skill copy log lines on stdout.
      expect(result.stdout).toContain("init: workspace ready");
      expect(result.stdout).toContain("init: skills copied");

      for (const dir of ["sources", "state", "items", "research", "templates"]) {
        expect(existsSync(join(workdir, dir))).toBe(true);
      }
      // Engine SKILLs (SSoT) under .agents/skills/.
      for (const skill of ["research", "review", "update"]) {
        expect(existsSync(join(workdir, ".agents", "skills", skill, "SKILL.md"))).toBe(true);
      }
      // Claude Code slash-command wrappers under .claude/skills/ (ADR-0007
      // revision via #75). dismiss is here but NOT in engine skills since the
      // dismiss command does not invoke an agent.
      for (const skill of ["research", "review", "update", "dismiss"]) {
        expect(existsSync(join(workdir, ".claude", "skills", skill, "SKILL.md"))).toBe(true);
      }
      // Gemini CLI slash commands under .gemini/commands/ (ADR-0007 revision
      // via #78): native TOML format Gemini CLI surfaces as /research etc.
      // dismiss appears here too (same asymmetry as .claude/skills/).
      for (const command of ["research", "review", "update", "dismiss"]) {
        expect(existsSync(join(workdir, ".gemini", "commands", `${command}.toml`))).toBe(true);
      }
      // Workspace-root AGENTS.md (ADR-0007 revision via #77): agent-agnostic
      // instructions auto-read by Codex / Gemini / Copilot when opened in
      // the workspace.
      expect(existsSync(join(workdir, "AGENTS.md"))).toBe(true);
    });

    it("--no-claude-skills skips .claude/skills/ but still writes engine SKILLs", async () => {
      const workdir = await mkdtemp(join(tmpdir(), "aw-e2e-init-nocs-"));
      const result = await runCli(["init", "--no-claude-skills"], { cwd: workdir });

      expect(result.code, `stderr: ${result.stderr}`).toBe(0);
      // Engine SKILLs still written.
      for (const skill of ["research", "review", "update"]) {
        expect(existsSync(join(workdir, ".agents", "skills", skill, "SKILL.md"))).toBe(true);
      }
      // .claude/skills/ should not exist at all.
      expect(existsSync(join(workdir, ".claude", "skills"))).toBe(false);
    });

    it("--no-gemini-commands skips .gemini/commands/ but still writes engine SKILLs", async () => {
      const workdir = await mkdtemp(join(tmpdir(), "aw-e2e-init-nogc-"));
      const result = await runCli(["init", "--no-gemini-commands"], { cwd: workdir });

      expect(result.code, `stderr: ${result.stderr}`).toBe(0);
      // Engine SKILLs still written (SSoT layer, always on).
      for (const skill of ["research", "review", "update"]) {
        expect(existsSync(join(workdir, ".agents", "skills", skill, "SKILL.md"))).toBe(true);
      }
      // Claude discovery skills still written (independent of gemini opt-out).
      for (const skill of ["research", "review", "update", "dismiss"]) {
        expect(existsSync(join(workdir, ".claude", "skills", skill, "SKILL.md"))).toBe(true);
      }
      // .gemini/commands/ should not exist at all.
      expect(existsSync(join(workdir, ".gemini", "commands"))).toBe(false);
    });
  });

  describe("scenario B: source add / list / remove", () => {
    it("round-trips a source through add → list → remove", async () => {
      const workdir = await mkdtemp(join(tmpdir(), "aw-e2e-source-"));
      await runCli(["init"], { cwd: workdir });

      const add = await runCli(
        ["source", "add", "smoke-blog", "--kind", "rss", "--url", "https://example.com/feed.xml"],
        { cwd: workdir },
      );
      expect(add.code, `stderr: ${add.stderr}`).toBe(0);
      expect(existsSync(join(workdir, "sources", "smoke-blog.yaml"))).toBe(true);

      const list = await runCli(["source", "list"], { cwd: workdir });
      expect(list.code, `stderr: ${list.stderr}`).toBe(0);
      expect(list.stdout).toContain("smoke-blog");
      expect(list.stdout).toContain("rss");

      const remove = await runCli(["source", "remove", "smoke-blog"], { cwd: workdir });
      expect(remove.code, `stderr: ${remove.stderr}`).toBe(0);
      expect(existsSync(join(workdir, "sources", "smoke-blog.yaml"))).toBe(false);
    });
  });

  describe("scenario C: dismiss (LLM-free)", () => {
    it("transitions a detected item to dismissed", async () => {
      const workdir = await mkdtemp(join(tmpdir(), "aw-e2e-dismiss-"));
      await runCli(["init"], { cwd: workdir });

      const itemId = "smoke-item-abcdef12";
      const sourceId = "smoke-source";
      await mkdir(join(workdir, "items", sourceId), { recursive: true });
      await writeFile(
        join(workdir, "items", sourceId, `${itemId}.yaml`),
        stringifyYaml({
          id: itemId,
          sourceId,
          title: "Smoke item",
          url: "https://example.com/smoke",
          fetchedAt: "2026-05-15T00:00:00.000Z",
          matchedKeywords: ["smoke"],
          status: "detected",
        }),
        "utf8",
      );

      const result = await runCli(["dismiss", itemId], { cwd: workdir });
      expect(result.code, `stderr: ${result.stderr}`).toBe(0);

      const after = parseYaml(
        await readFile(join(workdir, "items", sourceId, `${itemId}.yaml`), "utf8"),
      );
      expect(after.status).toBe("dismissed");
    });
  });

  describe("scenario D: research --agent claude-code (fake binary)", () => {
    it("generates a valid v1 research file and transitions item to researched", async () => {
      const workdir = await mkdtemp(join(tmpdir(), "aw-e2e-research-"));
      const binDir = join(workdir, "_bin");
      await installFakeClaude(binDir);
      await runCli(["init"], { cwd: workdir });

      const itemId = "smoke-item-12345678";
      const sourceId = "smoke-source";
      await mkdir(join(workdir, "items", sourceId), { recursive: true });
      await writeFile(
        join(workdir, "items", sourceId, `${itemId}.yaml`),
        stringifyYaml({
          id: itemId,
          sourceId,
          title: "Smoke item for research",
          url: "https://example.com/smoke",
          fetchedAt: "2026-05-15T00:00:00.000Z",
          matchedKeywords: ["smoke"],
          status: "detected",
        }),
        "utf8",
      );

      const result = await runCli(["research", itemId, "--agent", "claude-code"], {
        cwd: workdir,
        extraPath: binDir,
      });
      expect(result.code, `stderr: ${result.stderr}\nstdout: ${result.stdout}`).toBe(0);

      // Item status transitioned.
      const item = parseYaml(
        await readFile(join(workdir, "items", sourceId, `${itemId}.yaml`), "utf8"),
      );
      expect(item.status).toBe("researched");

      // Research file was written with valid frontmatter (id contains
      // YYYYMMDD prefix + sourceId-slug-of-title + _v1).
      const researchMatch = result.stdout.match(/research\/([^.\s]+\.md)/);
      expect(researchMatch).not.toBeNull();
      const researchPath = join(workdir, "research", researchMatch?.[1] ?? "MISSING");
      expect(existsSync(researchPath)).toBe(true);
      const { fm } = parseFrontmatter(await readFile(researchPath, "utf8"));
      expect(fm.agent).toBe("claude-code");
      expect(fm.itemIds).toEqual([itemId]);
      expect(fm.supersedes).toBeNull();
      expect(fm.reviewedAt).toBeNull();
      expect(fm.reviewedBy).toBeNull();
      // v1 invariant: id ends in _v1.
      expect(fm.id).toMatch(/_v1$/);
    });
  });

  describe("scenario E: update --agent claude-code (fake binary, supersedes + status-invariance)", () => {
    it("generates v2 with supersedes pointing to v1; items.yaml status is unchanged", async () => {
      const workdir = await mkdtemp(join(tmpdir(), "aw-e2e-update-"));
      const binDir = join(workdir, "_bin");
      await installFakeClaude(binDir);
      await runCli(["init"], { cwd: workdir });

      const itemId = "smoke-item-aabbccdd";
      const sourceId = "smoke-source";
      await mkdir(join(workdir, "items", sourceId), { recursive: true });
      await writeFile(
        join(workdir, "items", sourceId, `${itemId}.yaml`),
        stringifyYaml({
          id: itemId,
          sourceId,
          title: "Smoke item for update",
          url: "https://example.com/smoke",
          fetchedAt: "2026-05-15T00:00:00.000Z",
          matchedKeywords: ["smoke"],
          status: "reviewed",
        }),
        "utf8",
      );

      // Hand-craft a v1 research file. (We skip running the research
      // subcommand first to keep scenario E isolated and fast.)
      const v1Id = `20260510_smoke-source-smoke-item-for-update_v1`;
      const v1Path = join(workdir, "research", `${v1Id}.md`);
      const v1Yaml = stringifyYaml({
        id: v1Id,
        itemIds: [itemId],
        agent: "claude-code",
        templateId: "default",
        createdAt: "2026-05-10T00:00:00.000Z",
        updatedAt: null,
        reviewedAt: "2026-05-12T00:00:00.000Z",
        reviewedBy: "codex-cli",
        supersedes: null,
      });
      await writeFile(v1Path, `---\n${v1Yaml}---\n\n# v1 body\n`, "utf8");

      const result = await runCli(["update", v1Id, "--agent", "claude-code"], {
        cwd: workdir,
        extraPath: binDir,
      });
      expect(result.code, `stderr: ${result.stderr}\nstdout: ${result.stdout}`).toBe(0);

      // v2 file exists with supersedes pointing at v1.
      const v2Path = join(workdir, "research", `${v1Id.replace(/_v1$/, "_v2")}.md`);
      expect(existsSync(v2Path)).toBe(true);
      const { fm: v2Fm } = parseFrontmatter(await readFile(v2Path, "utf8"));
      expect(v2Fm.supersedes).toBe(v1Id);
      // v+1 invariant: review state reset (ADR-0003).
      expect(v2Fm.reviewedAt).toBeNull();
      expect(v2Fm.reviewedBy).toBeNull();
      // createdAt preserved from predecessor.
      expect(v2Fm.createdAt).toBe("2026-05-10T00:00:00.000Z");

      // ADR-0008 invariance: items.yaml status is unchanged (still reviewed).
      const item = parseYaml(
        await readFile(join(workdir, "items", sourceId, `${itemId}.yaml`), "utf8"),
      );
      expect(item.status).toBe("reviewed");

      // Immutable history: v1 file unchanged.
      const { fm: v1Fm } = parseFrontmatter(await readFile(v1Path, "utf8"));
      expect(v1Fm.reviewedBy).toBe("codex-cli");
      expect(v1Fm.supersedes).toBeNull();
    });
  });

  describe("scenario F: watch run --source <id> (RSS fixture via local HTTP server)", () => {
    // Phase 1 fetch path (#18) covered through the binary boundary. tests/core/feeds/rss
    // exercises the adapter with vi.spyOn(fetch); that mock cannot survive a child
    // subprocess so we serve the same fixture over a local HTTP server bound to port
    // 0 (kernel-assigned, no collision risk under parallel vitest workers).
    it("fetches an RSS source through the built binary and writes items/<sourceId>/<itemId>.yaml", async () => {
      const workdir = await mkdtemp(join(tmpdir(), "aw-e2e-watch-"));
      await runCli(["init"], { cwd: workdir });

      // Minimal RSS 2.0 envelope with one item that matches the keyword we
      // configure below. Two items would exercise dedup but mask the
      // "did any item land?" failure mode we actually care about here.
      const rssXml = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<rss version="2.0">',
        "  <channel>",
        "    <title>Smoke Blog</title>",
        "    <link>https://example.com/</link>",
        "    <description>e2e fixture</description>",
        "    <item>",
        "      <title>claude code update v0.1</title>",
        "      <link>https://example.com/posts/claude-code-v0-1</link>",
        '      <guid isPermaLink="false">smoke-e2e-1</guid>',
        "      <pubDate>Sun, 10 May 2026 00:00:00 GMT</pubDate>",
        "      <description>release notes for claude code</description>",
        "    </item>",
        "  </channel>",
        "</rss>",
      ].join("\n");

      // Set up the local HTTP server. The first listen happens before we
      // know the port, so url is captured inside the handler via
      // `server.address()` after listen() resolves.
      let server: Server | null = null;
      try {
        server = createServer((_req, res) => {
          res.writeHead(200, { "Content-Type": "application/rss+xml; charset=utf-8" });
          res.end(rssXml);
        });
        await new Promise<void>((resolveListen, rejectListen) => {
          server?.once("error", rejectListen);
          server?.listen(0, "127.0.0.1", () => resolveListen());
        });
        const port = (server.address() as AddressInfo).port;
        const feedUrl = `http://127.0.0.1:${port}/feed.xml`;

        // ADR-0006 / src/core/filter.ts: empty keywords means "match nothing"
        // (firehose guard). We must pass --keywords for items to survive the
        // filter and reach disk.
        const add = await runCli(
          ["source", "add", "smoke-rss", "--kind", "rss", "--url", feedUrl, "--keywords", "claude"],
          { cwd: workdir },
        );
        expect(add.code, `stderr: ${add.stderr}`).toBe(0);

        // The shared fetch wrapper enforces an SSRF host blocklist
        // (ADR-0009 §D5b); the fixture serves on 127.0.0.1 so we have to
        // opt that loopback host into the allowlist for this test only.
        const watch = await runCli(["watch", "run", "--source", "smoke-rss"], {
          cwd: workdir,
          extraEnv: { RADAR_FETCH_HOST_ALLOWLIST: "127.0.0.1" },
        });
        expect(watch.code, `stderr: ${watch.stderr}\nstdout: ${watch.stdout}`).toBe(0);
        expect(watch.stdout).toMatch(/1 new item\(s\)/);

        // An item file landed under items/smoke-rss/. The filename is the
        // sanitized id; we discover it rather than reconstruct the derivation.
        const itemsDir = join(workdir, "items", "smoke-rss");
        expect(existsSync(itemsDir)).toBe(true);
        const files = readdirSync(itemsDir).filter((f) => f.endsWith(".yaml"));
        expect(files).toHaveLength(1);

        const itemYaml = await readFile(join(itemsDir, files[0]), "utf8");
        const item = parseYaml(itemYaml);
        expect(item.sourceId).toBe("smoke-rss");
        expect(item.title).toBe("claude code update v0.1");
        expect(item.url).toBe("https://example.com/posts/claude-code-v0-1");
        expect(item.status).toBe("detected");
        // Filter matched on "claude" — recorded for downstream commands.
        expect(item.matchedKeywords).toContain("claude");

        // State file was persisted with the seen id so a second `watch run`
        // would not re-emit it.
        const statePath = join(workdir, "state", "smoke-rss.yaml");
        expect(existsSync(statePath)).toBe(true);
        const state = parseYaml(await readFile(statePath, "utf8"));
        expect(state.sourceId).toBe("smoke-rss");
        expect(state.lastSeenIds.length).toBeGreaterThan(0);
      } finally {
        if (server) {
          await new Promise<void>((resolveClose) => server?.close(() => resolveClose()));
        }
      }
    });
  });

  describe("scenario G: review --agent claude-code (fake binary, reviewedAt stamp + status invariance)", () => {
    // Mirror of scenario E (update) but for review: stamps reviewedAt /
    // reviewedBy in the research frontmatter and transitions linked items
    // from researched → reviewed via the workspace-level atomic snapshot
    // (src/cli/review.ts).
    it("stamps reviewedAt/reviewedBy and transitions linked item to reviewed", async () => {
      const workdir = await mkdtemp(join(tmpdir(), "aw-e2e-review-"));
      const binDir = join(workdir, "_bin");
      await installFakeClaudeReviewer(binDir);
      await runCli(["init"], { cwd: workdir });

      const itemId = "smoke-item-deadbeef";
      const sourceId = "smoke-source";
      await mkdir(join(workdir, "items", sourceId), { recursive: true });
      await writeFile(
        join(workdir, "items", sourceId, `${itemId}.yaml`),
        stringifyYaml({
          id: itemId,
          sourceId,
          title: "Smoke item for review",
          url: "https://example.com/smoke",
          fetchedAt: "2026-05-15T00:00:00.000Z",
          matchedKeywords: ["smoke"],
          status: "researched",
        }),
        "utf8",
      );

      // Hand-craft a v1 research file (pre-review state: reviewedAt/By null).
      const v1Id = `20260512_smoke-source-smoke-item-for-review_v1`;
      const v1Path = join(workdir, "research", `${v1Id}.md`);
      const v1Yaml = stringifyYaml({
        id: v1Id,
        itemIds: [itemId],
        agent: "claude-code",
        templateId: "default",
        createdAt: "2026-05-12T00:00:00.000Z",
        updatedAt: null,
        reviewedAt: null,
        reviewedBy: null,
        supersedes: null,
      });
      await writeFile(v1Path, `---\n${v1Yaml}---\n\n# v1 body\n`, "utf8");

      // Use codex-cli as the reviewer to make the cross-agent pattern obvious
      // (the underlying fake binary is still `claude` on PATH; the adapter
      // dispatched is the one in registry for codex-cli, so we keep the
      // simpler case here and use claude-code as the reviewer agent too).
      const result = await runCli(["review", v1Id, "--agent", "claude-code"], {
        cwd: workdir,
        extraPath: binDir,
      });
      expect(result.code, `stderr: ${result.stderr}\nstdout: ${result.stdout}`).toBe(0);

      // Research file has the review stamp.
      const { fm } = parseFrontmatter(await readFile(v1Path, "utf8"));
      expect(fm.reviewedAt).not.toBeNull();
      expect(fm.reviewedBy).toBe("claude-code");
      // Immutable fields preserved.
      expect(fm.id).toBe(v1Id);
      expect(fm.createdAt).toBe("2026-05-12T00:00:00.000Z");
      expect(fm.supersedes).toBeNull();

      // Linked item transitioned to reviewed.
      const item = parseYaml(
        await readFile(join(workdir, "items", sourceId, `${itemId}.yaml`), "utf8"),
      );
      expect(item.status).toBe("reviewed");
    });
  });
});

/**
 * Fake `claude` binary that performs a minimal review: reads the review
 * stdin payload, parses the research file at `researchPath`, and rewrites
 * its frontmatter with `reviewedAt` / `reviewedBy` stamped per the
 * adapter contract. The body gets an appended `## レビュー` section to
 * mirror what a real agent would do (without actually critiquing).
 *
 * Kept out of installFakeClaude() so the research/update fake stays minimal
 * and the review fake can evolve independently as the review contract
 * grows.
 */
async function installFakeClaudeReviewer(binDir: string): Promise<void> {
  await mkdir(binDir, { recursive: true });
  const script = `#!/usr/bin/env node
const fs = require("node:fs");

let stdin = "";
process.stdin.setEncoding("utf8");
process.stdin.on("data", (c) => { stdin += c; });
process.stdin.on("end", () => {
  let req;
  try { req = JSON.parse(stdin); } catch (e) {
    console.error("fake-claude-reviewer: bad stdin:", e.message);
    process.exit(2);
  }
  const { researchPath, agent, researchFrontmatter } = req;
  if (!researchPath || !agent || !researchFrontmatter) {
    console.error("fake-claude-reviewer: missing fields");
    process.exit(2);
  }
  // Rewrite frontmatter with the review stamp. Preserve every other field
  // verbatim — src/cli/review.ts checks for drift on id/agent/createdAt/
  // itemIds/templateId/supersedes and rolls back if any changed.
  const stamped = {
    ...researchFrontmatter,
    reviewedAt: new Date().toISOString(),
    reviewedBy: agent,
  };
  const fmLines = [
    "---",
    "id: " + stamped.id,
    "itemIds:",
    ...stamped.itemIds.map((id) => "  - " + id),
    "agent: " + stamped.agent,
    "templateId: " + stamped.templateId,
    "createdAt: " + stamped.createdAt,
    "updatedAt: " + (stamped.updatedAt === null ? "null" : stamped.updatedAt),
    "reviewedAt: " + stamped.reviewedAt,
    "reviewedBy: " + stamped.reviewedBy,
    "supersedes: " + (stamped.supersedes === null ? "null" : stamped.supersedes),
    "---",
    "",
    "# v1 body (unchanged)",
    "",
    "## レビュー (" + agent + ", " + stamped.reviewedAt + ")",
    "",
    "Reviewed by fake-claude-reviewer for L4 smoke.",
    ""
  ];
  fs.writeFileSync(researchPath, fmLines.join("\\n"), "utf8");
  console.log("fake-claude-reviewer: stamped " + researchPath);
});
`;
  const scriptPath = join(binDir, "claude");
  await writeFile(scriptPath, script, "utf8");
  await chmod(scriptPath, 0o755);
}
